### PR TITLE
OpenQASM circuit drawer

### PR DESCRIPTION
**Pull request by CalebMcIrvinGitHub**
*issue tag, if exist*
https://github.com/qBraid/qBraid/issues/227

## Changes:
Added a circuit drawer for OpenQASM 3.0, takes in an OpenQASM filename and outputs a textual representation of the circuit. Currently functional on a limited gate set with some logic simplifications. Further issues will expand functionality.

## Details or comments:

I'm unsure what unit tests would be beneficial for this feature, Any suggestions/comments with respect to the visual representation or logical implementation of the code would also be appreciated.

## Checklist before merge
Add an `x` between the boxes braket that apply, meaning to complete the check before any merge happen, feel free to ask help if you are unsure about anything.

### General 
- [X] I have read the CONTRIBUTING doc.

- [x] ALL new features must include unit test to the test directory, codecov will check for any missing test code exist.

- [x] Ensure that all the test passes.

### CODE REVIEW

**Review by ryanhill1 — CHANGES_REQUESTED** [review]
Thanks for this PR! Couple of updates needing:

#### Circuit Coverage

As you noted, your function right now is working only for a limited gate set. This is a great first step, but we would love the openqasm circuit drawer to work for any circuit generated by the qBraid random qasm circuit function:

```python
from qbraid.interface import random_circuit, circuit_drawer

qasm_str = random_circuit("qasm")
```

#### Testing

You can write unit tests that draw a few known circuits and verifies that the output matches what you would expect by comparing string literals. You could use the following qiskit visualization test modules as reference:

- [`test_circuit_drawer.py`](https://github.com/Qiskit/qiskit-terra/blob/main/test/python/visualization/test_circuit_drawer.py)
- [`test_circuit_test_drawer`](https://github.com/Qiskit/qiskit-terra/blob/main/test/python/visualization/test_circuit_text_drawer.py)

#### Formatting, headers, docstrings

Make sure all added code passes tests 3 and 4 on the [pull request checklist](https://github.com/qBraid/qBraid/blob/main/CONTRIBUTING.md#pull-request-checklist), and that all functions adhere by the [docstrings](https://github.com/qBraid/qBraid/blob/main/CONTRIBUTING.md#docstrings) and [code style](https://github.com/qBraid/qBraid/blob/main/CONTRIBUTING.md#code-style) requirements to ensure that your code passes the [Formatting check](https://github.com/qBraid/qBraid/actions/runs/5106473770/jobs/9191922240?pr=247)

**Comment by ryanhill1** [comment]
@CalebMcIrvinGitHub Oh, no problem! Yeah I guess because it's an open PR any pushed commits after the initial review automatically re-request. Sorry for the confusion! When it's ready you can just drop a comment then so you can keep pushing commits

**Comment by CalebMcIrvinGitHub** [comment]
I've updated the logic to include all of the Qiskit standard gates found [here](https://qiskit.org/documentation/apidoc/circuit_library.html). `tox -e linters` passes without issue and headers are verified for the files I added. With respect to the first point from your comment above where the first register is not drawn, this is because the first qubit register is never accessed using `q[0]`. `draw_circuit("qubit[2] q;\ncx q[0], q[1];")` will access the first qubit register, I just chose not to extend registers beyond where they were first accessed. If it would be preferable to have all registers extend to the end of the circuit, potentially making the result more uniform, I can definitely do that as well.
```
q0------■
        |
     |----|
q1---| cx |
     |----|
```
Let me know what else still needs to be added / any bugs or issues you run across.

**Review by ryanhill1 — APPROVED** [review]
Hey there! These updates are a great step forward. As you mentioned in your [comment](https://github.com/qBraid/qBraid/pull/247#issuecomment-1585818051) I definitely think extending the registers would make the circuit more readable. There are a few more loose ends that I would like to address as well. But for the purposes of Unitary Hack, and since it closes today, I am going to accept the PR so that you can get the credit for the closed issue, but would love to continue to work with you on some the final improvements!

**Comment by ryanhill1** [comment]
@CalebMcIrvinGitHub For Unitary Hack, your PR is merged! But following up on https://github.com/qBraid/qBraid/pull/247#pullrequestreview-1477579685, I've just opened related issues https://github.com/qBraid/qBraid/issues/268, https://github.com/qBraid/qBraid/issues/269 which would be great for you to work on to finish up this circuit drawer function.

Thanks so much for your contributions!

**Comment by CalebMcIrvinGitHub** [comment]
Fantastic, I'll get to work on these two issues soon, they hopefully shouldn't take too long.

**Pull request merged**
