### PR TITLE
update using jax library

### PR DESCRIPTION
**Pull request by Hope-Alemayehu**
Changes
This PR updates the circuit_equality.py file using the JAX library, which significantly improves performance for calculations involving larger matrices. The code works well on my local machine, but I encountered challenges with testing due to dependency issues and conflicts with Python's custom random module.

[✅] I have read CONTRIBUTING.md.
[✅] All new code includes corresponding unit tests and satisfies code coverage.
[✅] API Reference docstrings and/or User Guide have been updated to account for new features.
[] All integration tests, including remote tests, are passing.
[] (Optional) My name and affiliation are added to CITATION.cff

### CODE REVIEW

**Review by ryanhill1 — CHANGES_REQUESTED** [review]
I wish it was as simple as just substituting out `numpy` for `jax.numpy`! There's many unit tests which aren't passing. Please take a look at [CONTRIBUTING.md](https://github.com/qBraid/qBraid/blob/main/CONTRIBUTING.md) for how you can run unit tests locally using either pytest or tox. Just adding your test code to the bottom of the file and running it as a script will surely cause the namespace errors with random that you encountered.

**Comment by Hope-Alemayehu** [comment]
i wish to comeback and work on this after this week with no bounties....I'm spent too much time to stop:)

**Comment by ryanhill1** [comment]
@Hope-Alemayehu Sounds great! If you're not worried about the bounties, then a pure numpy solution that optimizes the code would be more than sufficient to merge the PR as well! But if you would like to continue looking into JAX, that would be welcomed as well. Willing to help however I can!

**Comment by Hope-Alemayehu** [comment]
Thank you, I would like to continue looking into JAX.

**Pull request closed without merging**
